### ISSUE TITLE
quick question about this.

### ISSUE THREAD

**Issue by ecabigting** [mwd-au/MIGS-payment-gateway-MVC5#2]
that does this line exactly do?

`var secureHash = Request.QueryString["vpc_SecureHash"];`

and this one

`var txnResponseCode = Request.QueryString["vpc_TxnResponseCode"];`

**Comment by mwd-au** [comment]
If you download the MIGS Dev kit available from your bank or here (Virtual Payment Client - Developers Kit): http://www.anz.com/australia/business/merchant/DownloadDevKit.asp

**Checkout "577310_ANZ eGATE VIRTUAL PAYMENT CLIENT INTEGRATION GUIDE_88476.pdf"**

**vpc_SecureHash** = Used to allow the Virtual Payment Client to check the integrity of the transaction request.

**vpc_TxnResponseCode** = A response code that is generated by the Payment Server to indicate the status of the transaction. A vpc_TxnResponseCode of “0” (zero) indicates that the transaction was processed successfully and approved by the Acquiring Bank. Any other value indicates the transaction was declined.

Hope that helps :)
